### ISSUE TITLE
[FEAT] 환경 변수 관리

### ISSUE THREAD

**Issue by sanghyunna** [DowaDream/DowaDream-Server#4]
## Description
- django-environ 을 활용한 환경 변수 관리

## Branch
feat/#4-dotenv

## To-do list
- [x] django-environ 설치
- [x] settings.py 에서 .env 읽어오도록 설정
- [x] get_secrets() 사용 코드 대체
