### ISSUE TITLE
[FIX] 소셜로그인 수정

### ISSUE THREAD

**Issue by separk314** [DowaDream/DowaDream-Server#6]
## Description
- access token을 return하도록 수정

## Branch
fix/#6-login

## To-do list
- [x] BASE_URL 수정
- [x] allauth 버전 다운그레이드
- [x] access token 발급
- [x] views.py 파일 분리
